config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :groups
  resources :users, except: %i[ new create ]

  get ":group_link/users/new", to: "users#new"
  post ":group_link/users", to: "users#create", as: "new_user"
  get ":user_link/draw-participants", to: "draw_participants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :links, as: :linkable
  has_many :user_groups
  has_many :users, through: :user_groups

  validates :group_name, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :links, as: :linkable
  has_many :user_groups
  has_many :groups, through: :user_groups

  validates :username, presence: true
  validates :full_name, presence: true
  validates :email, presence: true
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/draw_participants_controller.rb
class DrawParticipantsController < ApplicationController
  before_action :set_user

  def index
    @users = User.select(:id, :username).where.not(id: @user.id).where(is_drawed: false).shuffle

    unless @users.empty?
      @drawed_participant = draw_participant()
    end
  end

  def draw_participant
    random_idx = rand(0..@users.count-1)

    participant = User.find(@users[random_idx].id)
    participant.update(is_drawed: true)

    @users[random_idx].username
  end

  private

  def set_user
    @user = User.find(Link.find_by_link(params[:user_link]).linkable_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include GroupsHelper

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    
    respond_to do |format|
      if @group.save
        generate_link()        
        format.html {}
        format.turbo_stream {}
      else
        format.html { render :new }
      end
    end
  end

  def generate_link
    @link = Link.create(link: SecureRandom.uuid, linkable: @group)
    @link = ENV["BASE_URL"] + "/" + @link.link + "/users/new"
  end

  private
  
  def group_params
    params.require(:group).permit(:group_name, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_group, only: %i[ create ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        LinkUserToGroupJob.perform_later(@user.id, @group.id)
        generate_link()

        format.html {}
        format.turbo_stream {}
      else
        format.html { render :new, notice: "Something went wrong, please try again." }
      end
    end
  end

  def generate_link
    @link = Link.create(link: SecureRandom.uuid, linkable: @user)
    @link = ENV["BASE_URL"] + "/" + @link.link + "/draw-participants"
  end

  private

  def user_params
    params.require(:user).permit(:username, :full_name, :email)
  end

  def set_group
    @group = Group.find(Link.find_by_link(params[:group_link]).linkable_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/draw_participants_helper.rb
module DrawParticipantsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/draw_participants/index.html.erb
<div>
  <% unless @users.empty? %>
    <ul>
      <% @users.each do |u| %>
      <li><%= u.username %></li>
    <% end %>
    </ul>  
    <%= @drawed_participant %>
    <button>Draw participants</button>
  <% else %>
    <p>There's no more participants to sort</p>
  <% end %>
</div>

app/views/groups/create.turbo_stream.erb
<%= turbo_stream.update "new_group", "" %>
<%= turbo_stream.append "new_group",
                        partial: "shared/link",
                        locals: {
                          link: @link,
                          title: "Use this link to register to the group and share it with your friends"
                        } %>

app/views/groups/new.html.erb
<div >

  <%= turbo_frame_tag "new_group", class: "w-full" do %>
    <h1 class="text-baseColor absolute text-3xl z-10 top-1/4 left-36">Please create your group</h1>
    <%= image_tag 'svg/Gift-1.svg', class: "absolute top-28 left-1/2 w-24" %>
    <%= image_tag 'svg/Gift-1-1.svg', class: "absolute top-3/4 left-2/3 w-24" %>
    <%= image_tag 'svg/Gift-1-2.svg', class: "absolute top-1/3 left-20 w-32" %>
    <%= image_tag 'svg/Gift-1-3.svg', class: "absolute top-2/3 left-28 w-24" %>
    <%= image_tag 'svg/Group.svg', class: "absolute top-2/2 right-16" %>
    <%= form_with model: @group, class: "flex flex-col justify-center items-center gap-2" do |f| %>
      <%= f.text_field :group_name, placeholder: "Group name", class: "w-full rounded-lg drop-shadow-lg border-none focus:outline-none focus:ring focus:ring-baseColor" %>
      <%= f.text_area :description, placeholder: "Description", class: "w-full rounded-lg drop-shadow-lg border-none focus:outline-none focus:ring focus:ring-baseColor" %>
      <%= f.submit "Create group", class: "bg-baseColor w-full text-white p-3.5 rounded-lg z-10" %>
    <% end %>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="w-full h-full flex flex-col sm:justify-center sm:items-center col-start-3 col-span-8">
  <figure class="w-full h-3/6 flex justify-center">
    <%= image_tag 'Illustration_home' %>
  </figure>
  <h1 class="text-3xl font-bold text-baseColor text-center w-3/4 mb-12">A gift for every reason and every season</h1>
  <%= link_to new_group_path, class: "bg-baseColor p-3 text-white text-xl w-full text-center rounded-md" do %>
    Get started <span>&#8250;</span>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiftExchanges</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container w-screen h-screen font-firaSans grid grid-cols-12">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_link.html.erb
<h1 class="text-baseColor text-center text-2xl">Group created successfully</h1>
<h4 class="text-baseColor text-center text-lg"><%= title %></h4>
<p class="text-link text-center text-lg mb-48"><%= link %></p>
<%= image_tag 'svg/waves-footer.svg', class: "absolute max-w-none w-screen bottom-0 left-0" %>

app/views/users/create.turbo_stream.erb
<%= turbo_stream.update "new_user", "" %>
<%= turbo_stream.append "new_user",
                        partial: "shared/link",
                        locals: {
                          link: @link,
                          title: "Use this link to draw participants"
                        } %>

app/views/users/new.html.erb
<div class="sm:col-start-3 sm:col-span-8 flex flex-col items-center justify-center">
  <%= turbo_frame_tag "new_user", class: "w-full" do %>
    <h1 class="text-baseColor absolute text-3xl z-10 top-1/4 left-36">Please register to your group</h1>
    <%= image_tag 'svg/Gift-1.svg', class: "absolute top-28 left-1/2 w-24" %>
    <%= image_tag 'svg/Gift-1-1.svg', class: "absolute top-3/4 left-2/3 w-24" %>
    <%= image_tag 'svg/Gift-1-2.svg', class: "absolute top-1/3 left-20 w-32" %>
    <%= image_tag 'svg/Gift-1-3.svg', class: "absolute top-2/3 left-28 w-24" %>
    <%= image_tag 'svg/Group.svg', class: "absolute top-2/2 right-16" %>
    <%= form_with model: @user, url: new_user_path, class: "flex flex-col justify-center items-center gap-2" do |f| %>
      <%= f.text_field :username, placeholder: "Username", class: "w-full rounded-lg drop-shadow-lg border-none focus:outline-none focus:ring focus:ring-baseColor font-light" %>
      <%= f.text_field :full_name, placeholder: "Full name", class: "w-full rounded-lg drop-shadow-lg border-none focus:outline-none focus:ring focus:ring-baseColor font-light" %>
      <%= f.email_field :email, placeholder: "Email", class: "w-full rounded-lg drop-shadow-lg border-none focus:outline-none focus:ring focus:ring-baseColor font-light" %>
      <%= f.submit "Create user", class: "bg-baseColor w-full text-white p-3.5 rounded-lg z-10"%>
    <% end %>
  <% end %>
</div>